kind = "web"
previewPath = "/"
title = "BAANS INFRA"
version = "1.0.0"
id = "artifacts/baans-infra"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18243

[services.development]
run = "pnpm --filter @workspace/baans-infra run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/baans-infra", "run", "build" ]
publicDir = "artifacts/baans-infra/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18243"
BASE_PATH = "/"
